name: Publish Android SDK

on:
  push:
    branches:
      - "eran/try-fix-github-release"
  workflow_dispatch:

jobs:
  build_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and Publish the SDK
        env:
          MAVEN_USER: ${{ secrets.MAVEN_USER }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        working-directory: ./
        run: |
          make publish
