name: Publish Android SDK 

on:
  workflow_dispatch:

jobs:
  build_publish:
    runs-on: mco-dev-small-x64

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and Publish the SDK
        env:
          MAVEN_USER: ${{ secrets.MAVEN_USER }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        working-directory: ./
        run: |
          make publish

